/**
 * Monster definitions. Each monster has stats for combat resolution
 * using the same D&D-adjacent math as the player (AC, attack bonus,
 * damage, initiative).
 */

import type { StatusEffects } from './combat';

export interface Monster {
  key: string;
  name: string;
  maxHp: number;
  ac: number;
  /** Bonus added to d20 attack rolls. */
  attackBonus: number;
  /** Base damage on a hit. */
  baseDamage: number;
  /** Added to initiative roll (higher = acts first). */
  speed: number;
  xpReward: number;
  goldReward: number;
  /** Flavor text shown at combat start. */
  description: string;
  /** Sprite color for procedural rendering. */
  color: string;
  /** Items dropped on defeat — { itemKey, dropChance (0-1) }. */
  loot: Array<{ itemKey: string; chance: number }>;
  /** Monster's elemental affinity. */
  element?: 'fire' | 'ice' | 'poison' | 'shadow' | 'physical';
  /** Element the monster is weak to (takes 1.5x damage). */
  weakness?: string;
  /** Element the monster resists (takes 0.5x damage). */
  resistance?: string;
  /** Flees or takes damage when within a lit Lantern's radius. */
  lightVulnerable?: boolean;
  /** Optional special ability. */
  special?: {
    name: string;
    /** Chance to use instead of normal attack (0-1). */
    chance: number;
    /** Damage multiplier (1.0 = same as base). */
    damageMult?: number;
    /** Status effect applied on hit. */
    applyStatus?: { effect: keyof StatusEffects; value: number };
    /** Self-heal amount. */
    selfHeal?: number;
    /** Flavor text for the combat log. */
    text: string;
  };
}

const MONSTERS: Record<string, Monster> = {
  training_dummy: {
    key: 'training_dummy', name: 'Training Dummy', maxHp: 100, ac: 10,
    attackBonus: 0, baseDamage: 0, speed: 0,
    xpReward: 0, goldReward: 0,
    description: 'Straw and burlap. It does not fight back — not really.',
    color: '#8a6a3a',
    loot: [],
    element: 'physical',
    special: {
      name: 'Flinch', chance: 0.3, damageMult: 0, text: '{name} wobbles. Nothing more.',
    },
  },
  wolf: {
    key: 'wolf',
    name: 'Dire Wolf',
    maxHp: 12,
    ac: 11,
    attackBonus: 3,
    baseDamage: 4,
    speed: 3,
    xpReward: 25,
    goldReward: 5,
    description: 'Grey fur, yellow eyes. It does not growl — it has already decided.',
    color: '#707070',
    element: 'physical',
    weakness: 'fire',
    loot: [
      { itemKey: 'wolf_pelt', chance: 0.7 },
      { itemKey: 'health_potion', chance: 0.2 },
      { itemKey: 'iron_ore', chance: 0.15 },
    ],
    special: { name: 'Lunge', chance: 0.25, damageMult: 1.5, text: '{name} lunges with terrible speed.' },
  },
  skeleton: {
    key: 'skeleton',
    name: 'Risen Bones',
    maxHp: 18,
    ac: 13,
    attackBonus: 2,
    baseDamage: 5,
    speed: 0,
    xpReward: 50,
    goldReward: 12,
    description: 'It assembles itself from the cairn floor, one joint at a time. It remembers how to hold a sword.',
    color: '#d0d0c0',
    element: 'shadow',
    weakness: 'fire',
    resistance: 'poison',
    loot: [
      { itemKey: 'bone_shard', chance: 0.8 },
      { itemKey: 'mana_potion', chance: 0.25 },
      { itemKey: 'shadow_essence', chance: 0.1 },
      { itemKey: 'iron_ore', chance: 0.2 },
    ],
    special: { name: 'Bone Throw', chance: 0.2, damageMult: 0.8, applyStatus: { effect: 'stun', value: 1 }, text: '{name} tears a rib from its own chest and hurls it.' },
  },
  hollow_knight: {
    key: 'hollow_knight',
    name: 'Hollow Knight',
    maxHp: 40,
    ac: 16,
    attackBonus: 5,
    baseDamage: 8,
    speed: 2,
    xpReward: 150,
    goldReward: 50,
    description: 'Rusted armor, no face behind the visor. It kneels, then stands, then does not kneel again.',
    color: '#506068',
    element: 'shadow',
    weakness: 'fire',
    resistance: 'physical',
    loot: [
      { itemKey: 'iron_sword', chance: 0.4 },
      { itemKey: 'iron_helm', chance: 0.3 },
      { itemKey: 'health_potion', chance: 0.5 },
      { itemKey: 'shadow_essence', chance: 0.3 },
      { itemKey: 'troll_heart', chance: 0.2 },
    ],
    special: { name: 'Shield Bash', chance: 0.3, damageMult: 1.4, applyStatus: { effect: 'stun', value: 1 }, text: '{name} drives its shield forward. The world rings.' },
  },
  spider: {
    key: 'spider',
    name: 'Cairn Spider',
    maxHp: 14,
    ac: 10,
    attackBonus: 4,
    baseDamage: 3,
    speed: 4,
    xpReward: 30,
    goldReward: 6,
    description: 'Eight legs, each ending in a barb. It moves without sound.',
    color: '#3a3a2a',
    element: 'poison',
    weakness: 'fire',
    loot: [
      { itemKey: 'shadow_essence', chance: 0.2 },
      { itemKey: 'health_potion', chance: 0.15 },
      { itemKey: 'spider_silk', chance: 0.5 },
      { itemKey: 'dungeon_key', chance: 0.15 },
    ],
    special: { name: 'Web Spit', chance: 0.3, damageMult: 0.5, applyStatus: { effect: 'stun', value: 1 }, text: '{name} spits a web. You struggle to move.' },
  },
  wraith: {
    key: 'wraith',
    name: 'Barrow Wraith',
    maxHp: 22,
    ac: 14,
    attackBonus: 4,
    baseDamage: 6,
    speed: 2,
    xpReward: 75,
    goldReward: 20,
    description: 'Cold light where eyes should be. It remembers being angry.',
    color: '#4060a0',
    element: 'shadow',
    weakness: 'fire',
    resistance: 'physical',
    loot: [
      { itemKey: 'shadow_essence', chance: 0.4 },
      { itemKey: 'mana_potion', chance: 0.3 },
      { itemKey: 'moonpetal', chance: 0.2 },
      { itemKey: 'wraith_dust', chance: 0.35 },
      { itemKey: 'boss_key', chance: 0.2 },
    ],
    special: { name: 'Soul Drain', chance: 0.25, damageMult: 1.2, selfHeal: 5, text: '{name} reaches through you. Something tears.' },
  },
  boar: {
    key: 'boar',
    name: 'Wild Boar',
    maxHp: 16,
    ac: 12,
    attackBonus: 3,
    baseDamage: 5,
    speed: 2,
    xpReward: 30,
    goldReward: 8,
    description: 'Tusks low, eyes red. It charges without warning.',
    color: '#8a6040',
    element: 'physical',
    weakness: 'fire',
    loot: [
      { itemKey: 'health_potion', chance: 0.25 },
      { itemKey: 'wolf_pelt', chance: 0.3 },
      { itemKey: 'iron_ore', chance: 0.1 },
    ],
    special: { name: 'Gore', chance: 0.3, damageMult: 1.8, applyStatus: { effect: 'bleed', value: 3 }, text: '{name} charges — tusks aimed low.' },
  },
  bandit: {
    key: 'bandit',
    name: 'Forest Bandit',
    maxHp: 20,
    ac: 13,
    attackBonus: 4,
    baseDamage: 5,
    speed: 2,
    xpReward: 45,
    goldReward: 18,
    description: 'A mask, a blade, a grudge. They stopped asking questions long ago.',
    color: '#5a4a3a',
    element: 'physical',
    weakness: 'shadow',
    loot: [
      { itemKey: 'iron_ore', chance: 0.3 },
      { itemKey: 'health_potion', chance: 0.3 },
      { itemKey: 'iron_sword', chance: 0.1 },
      { itemKey: 'leather_cap', chance: 0.15 },
    ],
    special: { name: 'Cheap Shot', chance: 0.2, damageMult: 1.3, applyStatus: { effect: 'poison', value: 2 }, text: '{name} feints, then strikes from below. A coated blade.' },
  },
  cave_bat: {
    key: 'cave_bat',
    name: 'Cave Bat',
    maxHp: 10,
    ac: 14,
    attackBonus: 5,
    baseDamage: 3,
    speed: 5,
    xpReward: 25,
    goldReward: 5,
    description: 'Fast, frantic, hard to hit. Where there is one, there are more.',
    color: '#3a3040',
    loot: [
      { itemKey: 'bone_shard', chance: 0.2 },
      { itemKey: 'health_potion', chance: 0.15 },
    ],
    element: 'physical',
    weakness: 'fire',
    special: { name: 'Swarm Dive', chance: 0.3, damageMult: 0.6, applyStatus: { effect: 'bleed', value: 2 }, text: '{name} dives in a frenzy of teeth and wing.' },
  },
  mine_golem: {
    key: 'mine_golem',
    name: 'Iron Golem',
    maxHp: 35,
    ac: 17,
    attackBonus: 4,
    baseDamage: 8,
    speed: 0,
    xpReward: 80,
    goldReward: 25,
    description: 'Ore and anger, shaped into something that walks. It does not tire.',
    color: '#606870',
    loot: [
      { itemKey: 'iron_ore', chance: 0.6 },
      { itemKey: 'iron_ore', chance: 0.3 },
      { itemKey: 'troll_heart', chance: 0.15 },
    ],
    element: 'physical',
    resistance: 'physical',
    weakness: 'shadow',
    special: { name: 'Earthshaker', chance: 0.25, damageMult: 1.6, applyStatus: { effect: 'stun', value: 1 }, text: '{name} slams the ground. The tunnel shakes.' },
  },
  bog_lurker: {
    key: 'bog_lurker',
    name: 'Bog Lurker',
    maxHp: 28,
    ac: 12,
    attackBonus: 5,
    baseDamage: 7,
    speed: 1,
    xpReward: 65,
    goldReward: 18,
    description: 'It rises from the water without warning. By the time you see it, it has already struck.',
    color: '#304828',
    loot: [
      { itemKey: 'moonpetal', chance: 0.3 },
      { itemKey: 'shadow_essence', chance: 0.2 },
      { itemKey: 'health_potion', chance: 0.25 },
    ],
    element: 'poison',
    weakness: 'fire',
    special: { name: 'Drag Under', chance: 0.3, damageMult: 1.3, applyStatus: { effect: 'stun', value: 1 }, text: '{name} grabs your ankle and pulls.' },
  },
  drowned_warden: {
    key: 'drowned_warden',
    name: 'The Drowned Warden',
    maxHp: 95,
    ac: 17,
    attackBonus: 6,
    baseDamage: 10,
    speed: 1,
    xpReward: 400,
    goldReward: 150,
    description: 'Waterlogged armor, barnacled sword. It was a guardian once. The water changed it but did not release it.',
    color: '#283848',
    loot: [
      { itemKey: 'shadow_essence', chance: 1.0 },
      { itemKey: 'wraith_dust', chance: 0.8 },
      { itemKey: 'steel_sword', chance: 0.4 },
      { itemKey: 'chainmail', chance: 0.4 },
      { itemKey: 'troll_heart', chance: 0.5 },
      { itemKey: 'warden_shield', chance: 0.3 },
      { itemKey: 'ring_of_the_deep', chance: 0.15 },
    ],
    element: 'shadow',
    weakness: 'fire',
    resistance: 'poison',
    special: { name: 'Tidal Slam', chance: 0.25, damageMult: 1.8, applyStatus: { effect: 'stun', value: 1 }, text: '{name} brings its sword down like a wave crashing.' },
  },
  fire_elemental: {
    key: 'fire_elemental',
    name: 'Fire Elemental',
    maxHp: 24,
    ac: 13,
    attackBonus: 5,
    baseDamage: 6,
    speed: 3,
    xpReward: 55,
    goldReward: 15,
    description: 'No shape. No bones. Only heat and intention.',
    color: '#e06020',
    loot: [
      { itemKey: 'shadow_essence', chance: 0.25 },
      { itemKey: 'health_potion', chance: 0.2 },
    ],
    element: 'fire',
    resistance: 'fire',
    weakness: 'ice',
    special: { name: 'Ignite', chance: 0.3, damageMult: 1.0, applyStatus: { effect: 'burn', value: 3 }, text: '{name} flares. Everything near it burns.' },
  },
  lava_drake: {
    key: 'lava_drake',
    name: 'Lava Drake',
    maxHp: 38,
    ac: 15,
    attackBonus: 5,
    baseDamage: 8,
    speed: 2,
    xpReward: 90,
    goldReward: 30,
    description: 'Scales of cooling stone. Eyes like embers. It does not breathe fire — it is fire.',
    color: '#a03010',
    loot: [
      { itemKey: 'troll_heart', chance: 0.3 },
      { itemKey: 'iron_ore', chance: 0.4 },
      { itemKey: 'shadow_essence', chance: 0.2 },
    ],
    element: 'fire',
    resistance: 'fire',
    weakness: 'ice',
    special: { name: 'Flame Breath', chance: 0.25, damageMult: 1.6, applyStatus: { effect: 'burn', value: 3 }, text: '{name} opens its jaws. The air itself catches fire.' },
  },
  ash_wraith: {
    key: 'ash_wraith',
    name: 'Ash Wraith',
    maxHp: 26,
    ac: 14,
    attackBonus: 5,
    baseDamage: 7,
    speed: 3,
    xpReward: 70,
    goldReward: 22,
    description: 'What remains when a fire dies and refuses to forget.',
    color: '#484040',
    loot: [
      { itemKey: 'wraith_dust', chance: 0.35 },
      { itemKey: 'shadow_essence', chance: 0.3 },
      { itemKey: 'moonpetal', chance: 0.15 },
    ],
    element: 'fire',
    weakness: 'shadow',
    special: { name: 'Ash Storm', chance: 0.25, damageMult: 0.8, applyStatus: { effect: 'stun', value: 1 }, text: '{name} erupts into a cloud of cinder and ash.' },
  },
  ember_knight: {
    key: 'ember_knight',
    name: 'Ember Knight',
    maxHp: 50,
    ac: 17,
    attackBonus: 6,
    baseDamage: 9,
    speed: 1,
    xpReward: 120,
    goldReward: 40,
    description: 'Armor red with heat. The sword glows. It has been standing here since the tower fell — and it has not cooled.',
    color: '#804020',
    loot: [
      { itemKey: 'iron_ore', chance: 0.5 },
      { itemKey: 'troll_heart', chance: 0.3 },
      { itemKey: 'steel_sword', chance: 0.15 },
      { itemKey: 'chainmail', chance: 0.1 },
      { itemKey: 'ember_crown', chance: 0.1 },
    ],
    element: 'fire',
    resistance: 'fire',
    weakness: 'ice',
    special: { name: 'Molten Strike', chance: 0.3, damageMult: 1.5, applyStatus: { effect: 'burn', value: 2 }, text: '{name} swings. The blade leaves a trail of sparks.' },
  },
  hollow_king: {
    key: 'hollow_king',
    name: 'The Hollow King',
    maxHp: 120,
    ac: 18,
    attackBonus: 7,
    baseDamage: 12,
    speed: 1,
    xpReward: 500,
    goldReward: 200,
    description: 'A crown of tarnished iron. It kneels to something deeper — something that has not yet stirred.',
    color: '#282040',
    element: 'shadow',
    weakness: 'fire',
    resistance: 'poison',
    loot: [
      { itemKey: 'shadow_essence', chance: 1.0 },
      { itemKey: 'troll_heart', chance: 0.8 },
      { itemKey: 'steel_sword', chance: 0.5 },
      { itemKey: 'chainmail', chance: 0.4 },
      { itemKey: 'kings_crown', chance: 0.3 },
    ],
    special: { name: 'Dark Command', chance: 0.2, damageMult: 2.0, text: '{name} raises one hand. Dark energy obeys.' },
  },
  frost_wolf: {
    key: 'frost_wolf', name: 'Frost Wolf', maxHp: 20, ac: 13, attackBonus: 4,
    baseDamage: 5, speed: 4, xpReward: 45, goldReward: 12,
    description: 'White fur, blue eyes. Its breath freezes the air between you.',
    color: '#a0c0e0',
    loot: [{ itemKey: 'wolf_pelt', chance: 0.4 }, { itemKey: 'moonpetal', chance: 0.2 }],
    element: 'ice', weakness: 'fire', resistance: 'ice',
    special: { name: 'Frost Bite', chance: 0.3, damageMult: 1.3, applyStatus: { effect: 'stun', value: 1 }, text: '{name} lunges — its jaws burn with cold.' },
  },
  ice_golem: {
    key: 'ice_golem', name: 'Ice Golem', maxHp: 45, ac: 16, attackBonus: 4,
    baseDamage: 9, speed: 0, xpReward: 100, goldReward: 35,
    description: 'Glacier made flesh. It moves like a mountain deciding to fall.',
    color: '#80a8c8',
    loot: [{ itemKey: 'iron_ore', chance: 0.5 }, { itemKey: 'shadow_essence', chance: 0.3 }, { itemKey: 'troll_heart', chance: 0.2 }],
    element: 'ice', weakness: 'fire', resistance: 'ice',
    special: { name: 'Avalanche', chance: 0.2, damageMult: 2.0, applyStatus: { effect: 'stun', value: 1 }, text: '{name} brings both fists down. The mountain obeys.' },
  },
  blizzard_wraith: {
    key: 'blizzard_wraith', name: 'Blizzard Wraith', maxHp: 30, ac: 15, attackBonus: 5,
    baseDamage: 7, speed: 3, xpReward: 85, goldReward: 28,
    description: 'Snow given hatred. It screams without a mouth.',
    color: '#c0d8f0',
    loot: [{ itemKey: 'wraith_dust', chance: 0.4 }, { itemKey: 'shadow_essence', chance: 0.3 }, { itemKey: 'moonpetal', chance: 0.2 }],
    element: 'ice', weakness: 'fire', resistance: 'ice',
    special: { name: 'White Out', chance: 0.25, damageMult: 1.0, applyStatus: { effect: 'stun', value: 2 }, text: '{name} screams. The world goes white.' },
  },
  frost_warden: {
    key: 'frost_warden', name: 'Frost Warden', maxHp: 55, ac: 17, attackBonus: 6,
    baseDamage: 10, speed: 1, xpReward: 130, goldReward: 45,
    description: 'Ice-bound armor, frozen blade. It guarded something once. The cold did not release it from its oath.',
    color: '#607890',
    loot: [{ itemKey: 'steel_sword', chance: 0.2 }, { itemKey: 'chainmail', chance: 0.2 }, { itemKey: 'shadow_essence', chance: 0.4 }, { itemKey: 'troll_heart', chance: 0.3 }, { itemKey: 'frost_plate', chance: 0.15 }],
    element: 'ice', weakness: 'fire', resistance: 'ice',
    special: { name: 'Glacial Slash', chance: 0.3, damageMult: 1.5, applyStatus: { effect: 'bleed', value: 3 }, text: '{name} cuts. The wound freezes before it bleeds.' },
  },
  crownless_one: {
    key: 'crownless_one',
    name: 'The Crownless One',
    maxHp: 200,
    ac: 20,
    attackBonus: 8,
    baseDamage: 14,
    speed: 2,
    xpReward: 1000,
    goldReward: 500,
    description: 'No crown. No throne. No kingdom. Only the memory of all three — and the will to reclaim them from the earth itself.',
    color: '#1a1028',
    loot: [
      { itemKey: 'shadow_essence', chance: 1.0 },
      { itemKey: 'shadow_essence', chance: 1.0 },
      { itemKey: 'troll_heart', chance: 1.0 },
      { itemKey: 'kings_crown', chance: 1.0 },
      { itemKey: 'void_edge', chance: 0.2 },
      { itemKey: 'ring_of_the_deep', chance: 0.25 },
    ],
    element: 'shadow',
    weakness: 'fire',
    resistance: 'poison',
    special: { name: 'Unmaking', chance: 0.2, damageMult: 2.5, text: '{name} speaks a word. The word unmakes.' },
  },
  the_forgotten: {
    key: 'the_forgotten',
    name: 'The Forgotten',
    maxHp: 300,
    ac: 22,
    attackBonus: 10,
    baseDamage: 18,
    speed: 3,
    xpReward: 2000,
    goldReward: 1000,
    description: 'It has no name. It has no face. It was here before the stones. It will be here after.',
    color: '#080010',
    loot: [
      { itemKey: 'kings_crown', chance: 1.0 },
      { itemKey: 'shadow_essence', chance: 1.0 },
      { itemKey: 'shadow_essence', chance: 1.0 },
      { itemKey: 'troll_heart', chance: 1.0 },
      { itemKey: 'void_edge', chance: 0.4 },
      { itemKey: 'shadow_cloak', chance: 0.3 },
    ],
    element: 'shadow',
    resistance: 'shadow',
    special: { name: 'Erasure', chance: 0.25, damageMult: 3.0, text: '{name} does not attack. Part of you simply ceases.' },
  },
  shade: {
    key: 'shade',
    name: 'Shade',
    maxHp: 14,
    ac: 12,
    attackBonus: 3,
    baseDamage: 5,
    speed: 4,
    xpReward: 60,
    goldReward: 10,
    description: 'A smear of darkness with hungry eyes. It only moves when unseen — and it does not love the light.',
    color: '#20102a',
    element: 'shadow',
    weakness: 'fire',
    resistance: 'shadow',
    lightVulnerable: true,
    loot: [
      { itemKey: 'shadow_essence', chance: 0.5 },
      { itemKey: 'mana_potion', chance: 0.2 },
    ],
    special: { name: 'Creep', chance: 0.2, damageMult: 1.3, text: '{name} slips out of the dark and bites.' },
  },

  // ─── Secret bosses (one per outdoor/dungeon zone) ─────────────
  // Optional end-of-zone fights. Hidden behind unique triggers (dusk
  // examine, Echo Stone hollow wall, lit braziers, tide pool at night,
  // half-buried anchor). Tuned 1.3–1.5× the zone's main boss HP.

  the_antlered: {
    key: 'the_antlered',
    name: 'The Antlered',
    maxHp: 60,
    ac: 15,
    attackBonus: 5,
    baseDamage: 9,
    speed: 3,
    xpReward: 220,
    goldReward: 65,
    description: 'A stag too tall, antlers grown into a crown of bone. The wood quietens when it lifts its head. It has been waiting at this oak longer than any tree should stand.',
    color: '#5a3a22',
    element: 'physical',
    weakness: 'fire',
    resistance: 'poison',
    loot: [
      { itemKey: 'crown_of_bone', chance: 1.0 },
      { itemKey: 'wolf_pelt', chance: 0.8 },
      { itemKey: 'moonpetal', chance: 0.7 },
      { itemKey: 'bone_shard', chance: 0.6 },
    ],
    special: { name: 'Antler Charge', chance: 0.3, damageMult: 1.6, applyStatus: { effect: 'bleed', value: 3 }, text: '{name} lowers its crown and runs you through.' },
  },

  loom_mother: {
    key: 'loom_mother',
    name: 'The Loom-Mother',
    maxHp: 60,
    ac: 14,
    attackBonus: 5,
    baseDamage: 8,
    speed: 4,
    xpReward: 240,
    goldReward: 70,
    description: 'A spider the size of a doorway. Her abdomen is grey and split, leaking pale silk. It was she who wove the cairn doors shut — and she has waited a long time for someone to undo the knot.',
    color: '#3a2a3a',
    element: 'poison',
    weakness: 'fire',
    resistance: 'physical',
    loot: [
      { itemKey: 'loom_mothers_eye', chance: 1.0 },
      { itemKey: 'spider_silk', chance: 1.0 },
      { itemKey: 'shadow_essence', chance: 0.7 },
      { itemKey: 'mana_potion', chance: 0.6 },
    ],
    special: { name: 'Cocoon', chance: 0.3, damageMult: 0.8, applyStatus: { effect: 'stun', value: 2 }, text: '{name} wraps a thread around your throat. The world tightens.' },
  },

  the_dredged: {
    key: 'the_dredged',
    name: 'The Dredged',
    maxHp: 130,
    ac: 17,
    attackBonus: 7,
    baseDamage: 12,
    speed: 1,
    xpReward: 520,
    goldReward: 180,
    description: 'A shipwreck that learned to walk. Rope and barnacle and the bones of a crew that never reached harbour. The anchor at its heart still drags the floor it cannot leave.',
    color: '#2a3848',
    element: 'shadow',
    weakness: 'fire',
    resistance: 'poison',
    loot: [
      { itemKey: 'salt_eaten_hook', chance: 1.0 },
      { itemKey: 'shadow_essence', chance: 1.0 },
      { itemKey: 'troll_heart', chance: 0.7 },
      { itemKey: 'wraith_dust', chance: 0.7 },
    ],
    special: { name: 'Anchor Drag', chance: 0.25, damageMult: 1.7, applyStatus: { effect: 'bleed', value: 4 }, text: '{name} swings the anchor low. The barnacles open you.' },
  },

  last_witness: {
    key: 'last_witness',
    name: 'The Last Witness',
    maxHp: 110,
    ac: 17,
    attackBonus: 6,
    baseDamage: 11,
    speed: 2,
    xpReward: 460,
    goldReward: 150,
    description: 'A figure in pale robes that have not been new in two centuries. The mage who sealed the tower kept one apprentice behind — to watch, to learn, to die last. She has done all three already, and is doing them again.',
    color: '#604068',
    element: 'shadow',
    weakness: 'ice',
    resistance: 'fire',
    loot: [
      { itemKey: 'witnesss_veil', chance: 1.0 },
      { itemKey: 'wraith_dust', chance: 0.8 },
      { itemKey: 'shadow_essence', chance: 0.7 },
      { itemKey: 'mana_potion', chance: 0.6 },
    ],
    special: { name: 'Long Vigil', chance: 0.3, damageMult: 1.5, applyStatus: { effect: 'burn', value: 3 }, text: '{name} speaks one of the words she was told to remember. The word burns.' },
  },

  drowned_lord: {
    key: 'drowned_lord',
    name: 'The Drowned Lord',
    maxHp: 250,
    ac: 19,
    attackBonus: 9,
    baseDamage: 15,
    speed: 2,
    xpReward: 1100,
    goldReward: 600,
    description: 'A shape too large for any tide-pool. Crown of rusted iron set into a brow that is half coral, half king. Tendrils trail back into water that cannot be following from anywhere on the map.',
    color: '#1a2438',
    element: 'shadow',
    weakness: 'fire',
    resistance: 'poison',
    loot: [
      { itemKey: 'the_drowned_crown', chance: 1.0 },
      { itemKey: 'shadow_essence', chance: 1.0 },
      { itemKey: 'troll_heart', chance: 1.0 },
      { itemKey: 'wraith_dust', chance: 0.8 },
      { itemKey: 'ring_of_the_deep', chance: 0.4 },
    ],
    special: { name: 'King-Tide', chance: 0.25, damageMult: 2.0, applyStatus: { effect: 'stun', value: 1 }, text: '{name} raises a hand. The ocean answers.' },
  },
};

export function getMonster(key: string): Monster {
  const m = MONSTERS[key];
  if (!m) throw new Error(`Unknown monster: ${key}`);
  return m;
}

export const ALL_MONSTERS = Object.values(MONSTERS);
